-- SELECIONAR TODOS PRODUTOS QUE SEJAM DO TIPO CHOCOLATE
SELECT PROD_NOME, PROD_QTD_ESTOQUE, MARCA_PROD_NOME
FROM PRODUTO 
INNER JOIN TIPO_PRODUTO 
	 ON PRODUTO.TPRO_ID = TIPO_PRODUTO.TPRO_ID
INNER JOIN MARCA_PRODUTO
	 ON PRODUTO.MARCA_PROD_ID=MARCA_PRODUTO.MARCA_PROD_ID
	 WHERE TIPO_PRODUTO.TPRO_NOME_TIPO_PROD='CHOCOLATE';

SELECT	p.Nome,
		p.QuantidadeEstoque,
		mp.Nome AS NomeMarca
	FROM PRODUTO p WITH(NOLOCK) 
		INNER JOIN TipoProduto tp WITH(NOLOCK) 
			 ON tp.IdTipoProduto = p.IdTipoProduto
		INNER JOIN MarcaProduto mp WITH(NOLOCK)
			 ON mp.IdMarcaProduto = p.IdMarcaProduto
	WHERE tp.IdTipoProduto = 1;

--listar o nome do produto, marca, valor de venda, valor de compra e quantidade de todos os produtos
SELECT PROD_NOME AS NOME_PRODUTO,MARCA_PROD_NOME AS MARCA_PRODUTO, PROD_VAL_COMPRA AS VALOR_COMPRA, PROD_VAL_VENDA AS VALOR_VENDA, PROD_QTD_ESTOQUE AS QUANTIDADE_ESTOQUE 
FROM PRODUTO
INNER JOIN MARCA_PRODUTO
	 ON PRODUTO.MARCA_PROD_ID=MARCA_PRODUTO.MARCA_PROD_ID

--listar o nome do produto, marca, tipo, nome do cliente, data da compra e
-- data de pagamento de todos os produtos pagos em janeiro de 2017
SELECT PROD_NOME,MARCA_PROD_NOME, TPRO_NOME_TIPO_PROD,VEN_DATA_VENDA, VEN_DATA_PAGAMENTO 
FROM VENDA_ITEM
INNER JOIN VENDA 
	ON VENDA_ITEM.VEN_ID=VENDA.VEN_ID
INNER JOIN PRODUTO
	ON VENDA_ITEM.PROD_ID=PRODUTO.PROD_ID
INNER JOIN MARCA_PRODUTO
	 ON PRODUTO.MARCA_PROD_ID=MARCA_PRODUTO.MARCA_PROD_ID
INNER JOIN TIPO_PRODUTO 
	 ON PRODUTO.TPRO_ID = TIPO_PRODUTO.TPRO_ID 
WHERE MONTH(VEN_DATA_PAGAMENTO)='01' AND YEAR(VEN_DATA_PAGAMENTO)='2017';

--listar o nome, sexo e status(ativo) de todos os clientes que fazem aniversario em abril
SELECT CLI_NOME, CLI_SEXO, CLI_ATIVO 
FROM CLIENTE
WHERE CLI_ATIVO=1 AND MONTH(CLI_DATA_NASC)='12'

SELECT	CLI_NOME, 
		CLI_SEXO, 
		CLI_ATIVO 
	FROM CLIENTE
	WHERE CLI_ATIVO=1 
		AND MONTH(CLI_DATA_NASC)='12'
		AND hauaha
		AND (hauahu OR ahauhaha)

--Listar o nome do cliente e quantidade de produtos diferentes comprados em 2017
SELECT CLI_NOME, COUNT(PROD_ID) AS QTD_PRODUTO_COMPRADOS

FROM VENDA
INNER JOIN VENDA_ITEM 
	ON VENDA_ITEM.VEN_ID=VENDA.VEN_ID
INNER  JOIN CLIENTE
	ON VENDA.CLI_ID=CLIENTE.CLI_ID
WHERE YEAR(VEN_DATA_VENDA)='2017'
GROUP BY CLI_NOME

--Listar o nome do produto e quantidade VENDIDOS EM 2017

SELECT PROD_NOME, SUM(VEN_ITEM_QTD) AS QTD_VENDIDA

FROM VENDA
INNER JOIN VENDA_ITEM
	ON VENDA.VEN_ID=VENDA_ITEM.VEN_ID
INNER JOIN PRODUTO
	ON VENDA_ITEM.PROD_ID=PRODUTO.PROD_ID
WHERE YEAR(VEN_DATA_VENDA)='2017'
GROUP BY PROD_NOME

--listar o nome, sexo e status de todos os clientes que não compraram

SELECT CLI_NOME, CLI_SEXO, CLI_ATIVO
FROM CLIENTE 
WHERE CLI_ID NOT IN(
SELECT cliente.CLI_ID FROM CLIENTE
INNER JOIN VENDA
	ON VENDA.CLI_ID=CLIENTE.CLI_ID)

SELECT	CLI_NOME, 
		CLI_SEXO, 
		CLI_ATIVO
	FROM CLIENTE 
	WHERE CLI_ID NOT IN
	(
		SELECT cliente.CLI_ID 
			FROM CLIENTE
				INNER JOIN VENDA
					ON VENDA.CLI_ID=CLIENTE.CLI_ID
	)

--listar o nome do cliente, sexo, quantidade de itens não pagos e data da primeira compra não paga
SELECT TOP 10 CLI_NOME, COUNT(VEN_DATA_VENDA), MAX(VEN_DATA_VENDA)AS DATA_ULTIMA_COMPRA, SUM(VEN_ITEM_QTD)ITENS_NAO_PAGOS
FROM CLIENTE
INNER JOIN VENDA 
	ON CLIENTE.CLI_ID= VENDA.CLI_ID
INNER JOIN VENDA_ITEM
	ON VEN_ITEM_ID=VENDA.VEN_ID	
WHERE   VEN_DATA_PAGAMENTO IS NULL
GROUP BY CLI_NOME

--listar o nome da marca, o valor total de lucro obtido e a quantidade total de produtos

SELECT MPROD.MARCA_PROD_NOME, SUM(PROD.PROD_VAL_VENDA-PROD.PROD_VAL_COMPRA) AS LUCRO_MARCA, SUM(VEN_I.VEN_ITEM_QTD)QTD_ITENS

FROM VENDA_ITEM VEN_I
INNER JOIN PRODUTO PROD
	ON PROD.PROD_ID=VEN_I.PROD_ID
INNER JOIN MARCA_PRODUTO MPROD
	ON PROD.MARCA_PROD_ID=MPROD.MARCA_PROD_ID
GROUP BY MPROD.MARCA_PROD_NOME

--listar o nome do produto, marca, valor de venda, valor de compra, nome do ultimo comprador e data da ultima compra

--Listar o nome da marca, e quantidade de produtos em estoque

SELECT MPROD.MARCA_PROD_NOME, SUM( PROD.PROD_QTD_ESTOQUE)AS QTD_ESTOQUE
FROM PRODUTO PROD
INNER JOIN MARCA_PRODUTO MPROD
	ON MPROD.MARCA_PROD_ID=PROD.MARCA_PROD_ID
GROUP BY MPROD.MARCA_PROD_NOME

--listar o nome, sexo, data de nascimento e quantidade comprada(somente paga)
SELECT TOP 15 CLI.CLI_NOME,CLI.CLI_SEXO, CLI.CLI_DATA_NASC,  SUM(VITEM.VEN_ITEM_QTD) AS QTD_COMPRADA

FROM VENDA VEN
INNER JOIN CLIENTE CLI
	ON CLI.CLI_ID=VEN.CLI_ID
INNER JOIN VENDA_ITEM VITEM
	ON VITEM.VEN_ID=VEN.VEN_ID

WHERE VEN.VEN_DATA_PAGAMENTO IS NOT NULL
GROUP BY CLI.CLI_NOME, CLI.CLI_SEXO, CLI.CLI_DATA_NASC
ORDER BY QTD_COMPRADA DESC

--listar o nome dos produtos que tenham a palavra "cola" em seu nome

SELECT *
FROM PRODUTO PROD
WHERE PROD.PROD_NOME LIKE '%COLA%'

--listar o nome, sexo e data de nascimento de todos os clientes ATIVOS

SELECT CLI.CLI_NOME, CLI.CLI_SEXO, CLI.CLI_DATA_NASC 
FROM CLIENTE CLI
WHERE CLI.CLI_ATIVO=1

--listar o nome, tipo, marca e valor de venda de todos os produtos que não foram vendidos

SELECT PROD.PROD_NOME,TPROD.TPRO_NOME_TIPO_PROD, MPROD.MARCA_PROD_NOME, PROD.PROD_VAL_VENDA
FROM PRODUTO PROD
INNER JOIN MARCA_PRODUTO MPROD
	ON PROD.MARCA_PROD_ID=MPROD.MARCA_PROD_ID
INNER JOIN TIPO_PRODUTO TPROD
	ON PROD.TPRO_ID=TPROD.TPRO_ID
WHERE PROD.PROD_ID NOT IN (
SELECT PROD.PROD_ID
FROM VENDA VEN
INNER JOIN VENDA_ITEM VITEM
	ON VEN.VEN_ID=VITEM.VEN_ID
INNER JOIN PRODUTO PROD
	ON PROD.PROD_ID=VITEM.VEN_ITEM_ID
INNER JOIN MARCA_PRODUTO MPROD
	ON MPROD.MARCA_PROD_ID=PROD.MARCA_PROD_ID )


--listar o nome, marca, quantidade vendida e valor do lucro obtido ((valor venda - valor compra) * quantidade vendida)
-- dos 10 produtos mais lucrativos (Somente produtos pagos)
SELECT TOP 10 PROD.PROD_NOME, MPROD.MARCA_PROD_NOME, SUM(VITEM.VEN_ITEM_QTD) AS QTD_VENDIDA,
SUM((PROD.PROD_VAL_VENDA-PROD.PROD_VAL_COMPRA)*VITEM.VEN_ITEM_QTD) AS LUCRO
FROM VENDA_ITEM VITEM
INNER JOIN PRODUTO PROD
	ON PROD.PROD_ID=VITEM.PROD_ID
INNER JOIN VENDA VEN
	ON VITEM.VEN_ID=VEN.VEN_ID
INNER JOIN MARCA_PRODUTO MPROD
	ON MPROD.MARCA_PROD_ID=PROD.PROD_ID
WHERE VEN.VEN_DATA_PAGAMENTO IS NOT NULL
GROUP BY PROD.PROD_NOME, MPROD.MARCA_PROD_NOME
ORDER BY LUCRO DESC

--listar o nome, marca, valor de compra, valor de venda e quantidade em estoque dos 10 produtos mais vendidos
SELECT PROD.PROD_NOME, MPROD.MARCA_PROD_NOME, PROD.PROD_VAL_COMPRA, PROD.PROD_VAL_VENDA, PROD.PROD_QTD_ESTOQUE, 
SUM(VITEM.VEN_ITEM_QTD)QTD_VENDIDA INTO #MAIS_VENDIDOS
FROM VENDA VEN
INNER JOIN VENDA_ITEM VITEM
	ON VEN.VEN_ID=VITEM.VEN_ID
INNER JOIN PRODUTO PROD
	ON PROD.PROD_ID=VITEM.PROD_ID
INNER JOIN MARCA_PRODUTO MPROD
	ON MPROD.MARCA_PROD_ID=PROD.MARCA_PROD_ID
GROUP BY PROD.PROD_NOME, MPROD.MARCA_PROD_NOME, PROD.PROD_VAL_COMPRA, PROD.PROD_VAL_VENDA, PROD.PROD_QTD_ESTOQUE
ORDER BY QTD_VENDIDA DESC

SELECT TOP 10 PROD_NOME, MARCA_PROD_NOME, PROD_VAL_COMPRA, PROD_VAL_VENDA, PROD_QTD_ESTOQUE FROM #MAIS_VENDIDOS
DROP TABLE #MAIS_VENDIDOS

--listar o nome do produto, marca, valor de venda, valor de compra, nome do ultimo comprador e data da ultima compra

SELECT PROD.PROD_NOME, MPROD.MARCA_PROD_NOME, PROD.PROD_VAL_VENDA, PROD.PROD_VAL_COMPRA, CLI_NOME,MAX( VEN_DATA_VENDA)

FROM VENDA VEN
INNER JOIN VENDA_ITEM VITEM
	ON VEN.VEN_ID=VITEM.VEN_ID
INNER JOIN PRODUTO PROD
	ON PROD.PROD_ID=VITEM.PROD_ID
INNER JOIN MARCA_PRODUTO MPROD
	ON MPROD.MARCA_PROD_ID=PROD.MARCA_PROD_ID
INNER JOIN CLIENTE CLI
	ON CLI.CLI_ID=VEN.CLI_ID
GROUP BY PROD.PROD_NOME,MPROD.MARCA_PROD_NOME, PROD.PROD_VAL_VENDA, PROD.PROD_VAL_COMPRA,CLI_NOME

--listar o nome do cliente, sexo, e media de tempo (minutos, horas ou dias) que ele demora para pagar
SELECT  TOP 10 CLI.CLI_NOME, CLI.CLI_SEXO, VEN.VEN_DATA_VENDA,VEN.VEN_DATA_PAGAMENTO,
DATEDIFF(day,VEN.VEN_DATA_VENDA,VEN.VEN_DATA_PAGAMENTO)AS DIAS_PARA_PAGAR

FROM VENDA VEN
INNER JOIN CLIENTE CLI
	ON VEN.CLI_ID=CLI.CLI_ID
WHERE VEN_DATA_PAGAMENTO IS NOT NULL
ORDER BY DIAS_PARA_PAGAR 

--listar o nome do produto, marca e porcentagem dos clientes que compraram. 
--EX: nome produto: laka, 41% dos usuarios compram(vendas pagas)
DECLARE @NOME VARCHAR

DECLARE @USUARIOS INT
 SELECT @USUARIOS = COUNT(CLI_ID) FROM CLIENTE;

SELECT PROD.PROD_NOME, ((COUNT(distinct VEN.CLI_ID))*100)/@USUARIOS AS CLI_COM_PRODUTO_PORCENTAGEM

FROM VENDA VEN
INNER JOIN VENDA_ITEM VITEM
	ON VEN.VEN_ID=VITEM.VEN_ID
INNER JOIN PRODUTO PROD
	ON PROD.PROD_ID=VITEM.PROD_ID
INNER JOIN MARCA_PRODUTO MPROD
	ON MPROD.MARCA_PROD_ID=PROD.MARCA_PROD_ID
WHERE VEN.VEN_DATA_PAGAMENTO IS NOT NULL
GROUP BY PROD.PROD_NOME, VEN.CLI_ID


SELECT PROD.PROD_NOME,COUNT( VEN.CLI_ID)

FROM VENDA VEN
INNER JOIN VENDA_ITEM VITEM
	ON VEN.VEN_ID=VITEM.VEN_ID
INNER JOIN PRODUTO PROD
	ON PROD.PROD_ID=VITEM.PROD_ID
INNER JOIN MARCA_PRODUTO MPROD
	ON MPROD.MARCA_PROD_ID=PROD.MARCA_PROD_ID
WHERE VEN.VEN_DATA_PAGAMENTO IS NOT NULL
GROUP BY PROD.PROD_NOME, VEN.CLI_ID




--listar o mes/ano,  a quantidade total de produtos vendidos (pagos) e a quantidade 
--total de produtos vendidos (não pagos) no mes/ano de referencia PARCIAL
 
--TESE 2 SEPARADA

SELECT  (CONVERT(VARCHAR(4),YEAR(VEN.VEN_DATA_VENDA)) + '-' + CONVERT(VARCHAR(02),MONTH(VEN.VEN_DATA_VENDA))) AS MES_COMPRA,
SUM(VITEM.VEN_ITEM_QTD) AS PRODUTOS_PAGOS
FROM VENDA_ITEM VITEM
INNER JOIN VENDA VEN
	ON VEN.VEN_ID=VITEM.VEN_ID
WHERE VEN.VEN_DATA_PAGAMENTO IS NOT NULL
GROUP BY (CONVERT(VARCHAR(4),YEAR(VEN.VEN_DATA_VENDA)) + '-' + CONVERT(VARCHAR(02),MONTH(VEN.VEN_DATA_VENDA)))

SELECT  (CONVERT(VARCHAR(4),YEAR(VEN.VEN_DATA_VENDA)) + '-' + CONVERT(VARCHAR(02),MONTH(VEN.VEN_DATA_VENDA))) AS MES_COMPRA,
SUM(VITEM.VEN_ITEM_QTD) AS PRODUTOS_NAO_PAGOS
FROM VENDA_ITEM VITEM
INNER JOIN VENDA VEN
	ON VEN.VEN_ID=VITEM.VEN_ID
WHERE VEN.VEN_DATA_PAGAMENTO IS NULL
GROUP BY (CONVERT(VARCHAR(4),YEAR(VEN.VEN_DATA_VENDA)) + '-' + CONVERT(VARCHAR(02),MONTH(VEN.VEN_DATA_VENDA)))


--listar o nome do cliente, sexo, idade e nome do produto favorito (mais comprado pelo cliente),
-- caso não possua deixar em branco
SELECT  cli.CLI_NOME,
		cli.CLI_SEXO,
		DATEDIFF(year,cli.CLI_DATA_NASC,GETDATE())AS Idade,
		aa.PROD_NOME
	FROM CLIENTE CLI
		OUTER APPLY	(
			SELECT top 1 PRO.PROD_NOME AS PROD_NOME, 
					SUM(VI.VEN_ITEM_QTD)  AS QTD_PRODUTO
				FROM VENDA VEN
					INNER JOIN VENDA_ITEM VI
						ON VEN.VEN_ID = VI.VEN_ID
					INNER JOIN PRODUTO PRO
						ON 	PRO.PROD_ID = VI.PROD_ID
				WHERE VEN.CLI_ID=CLI.CLI_ID	
				GROUP BY  PRO.PROD_NOME,VEN_ITEM_QTD
				ORDER BY VI.VEN_ITEM_QTD DESC
		)AA
	

	





SELECT  CLI.CLI_NOME AS NOME,
		PROD.PROD_NOME AS PROD_NOME, 
		SUM(VITEM.VEN_ITEM_QTD)  AS QTD_PRODUTO
	FROM CLIENTE CLI
		INNER JOIN VENDA VEN
			ON CLI.CLI_ID=VEN.CLI_ID
		INNER JOIN VENDA_ITEM VITEM
			ON VEN.VEN_ID = VITEM.VEN_ID
		INNER JOIN PRODUTO PROD
			ON 	PROD.PROD_ID = VITEM.PROD_ID	
	







select   count ( DISTINCT cli.cli_nome)
	from CLIENTE cli 
		inner join VENDA ven
			on ven.CLI_ID=cli.CLI_ID
		inner join VENDA_ITEM vi
			on vi.VEN_ID= ven.VEN_ID
			and VEN.VEN_DATA_PAGAMENTO IS NOT NULL
	where vi.PROD_ID=2

--listar o nome do produto, marca e porcentagem dos clientes que compraram. 
--EX: nome produto: laka, 41% dos usuarios compram(vendas pagas)
DECLARE @USUARIOS2 INT

SELECT @USUARIOS2 = COUNT(CLI_ID) 
	FROM CLIENTE;

SELECT  PROD.PROD_NOME as Nome, 
		((COUNT(distinct CLI.CLI_ID))*100)/@USUARIOS2 AS PorcentagemdosClientesCompraram
		--COUNT( CLI.CLI_ID) AS CLI_COM_PRODUTO_PORCENTAGEM
	FROM VENDA VEN
		INNER JOIN VENDA_ITEM VITEM
			ON VEN.VEN_ID=VITEM.VEN_ID
		INNER JOIN PRODUTO PROD
			ON PROD.PROD_ID=VITEM.PROD_ID
		INNER JOIN MARCA_PRODUTO MPROD
			ON MPROD.MARCA_PROD_ID=PROD.MARCA_PROD_ID
		INNER JOIN CLIENTE CLI
			ON CLI.CLI_ID =VEN.CLI_ID
	WHERE VEN.VEN_DATA_PAGAMENTO IS NOT NULL
	GROUP BY PROD.PROD_NOME 