USE [master]
GO

/****** Object:  Database [Mercado]    Script Date: 06/10/2017 14:38:24 ******/
CREATE DATABASE [Mercado]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Merccado', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Merccado.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Merccado_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Merccado_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Mercado] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Mercado].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Mercado] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Mercado] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Mercado] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Mercado] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Mercado] SET ARITHABORT OFF 
GO

ALTER DATABASE [Mercado] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Mercado] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Mercado] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Mercado] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Mercado] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Mercado] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Mercado] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Mercado] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Mercado] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Mercado] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Mercado] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Mercado] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Mercado] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Mercado] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Mercado] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Mercado] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Mercado] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Mercado] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Mercado] SET  MULTI_USER 
GO

ALTER DATABASE [Mercado] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Mercado] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Mercado] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Mercado] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Mercado] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Mercado] SET  READ_WRITE 
GO

