USE [master]
GO

/****** Object:  Database [SMN_Musicas]    Script Date: 06/10/2017 14:36:39 ******/
CREATE DATABASE [SMN_Musicas]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SMN_Musicas', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SMN_Musicas.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SMN_Musicas_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SMN_Musicas_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SMN_Musicas] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SMN_Musicas].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SMN_Musicas] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SMN_Musicas] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SMN_Musicas] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SMN_Musicas] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SMN_Musicas] SET ARITHABORT OFF 
GO

ALTER DATABASE [SMN_Musicas] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [SMN_Musicas] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SMN_Musicas] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SMN_Musicas] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SMN_Musicas] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SMN_Musicas] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SMN_Musicas] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SMN_Musicas] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SMN_Musicas] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SMN_Musicas] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SMN_Musicas] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SMN_Musicas] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SMN_Musicas] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SMN_Musicas] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SMN_Musicas] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SMN_Musicas] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [SMN_Musicas] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SMN_Musicas] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SMN_Musicas] SET  MULTI_USER 
GO

ALTER DATABASE [SMN_Musicas] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SMN_Musicas] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SMN_Musicas] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SMN_Musicas] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SMN_Musicas] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SMN_Musicas] SET  READ_WRITE 
GO

